app = "chriszulu-f1-api"
primary_region = "lhr"

[build]
  image = "ghcr.io/slowlydev/f1-dash-api:latest"

[env]
  RUST_LOG = "api=info"
  ADDRESS = "0.0.0.0:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
